[tool.poetry]
name = "arq-emulator"
version = "0.1.0"
description = ""
authors = ["Yuri Araújo <araujoyuri@edu.unifor.br>"]

[tool.poetry.dependencies]
python = "3.7.*"

[tool.poetry.dev-dependencies]
